name: .NET CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Build Docker Image
      run: docker build -t devopsdemoapi .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: docker tag devopsdemoapi joyalwiz/devopsdemoapi:latest

    - name: Push Docker Image
      run: docker push joyalwiz/devopsdemoapi:latest
